### ISSUE TITLE
Evaluate Stanza

### ISSUE THREAD

**Issue by dveselov** [natasha/naeval#1]
Hi,
Stanford released a new spacy-like framework for NLP named Stanza - https://github.com/stanfordnlp/stanza
It features NER model (trained on WikiNER dataset) and dependency parsing model (trained on three datasets: gsd, syntagrus, taiga) - https://stanfordnlp.github.io/stanza/models.html
It would be great to see it results in this comparison.

**Comment by kuk** [comment]
WikiNER плохой для русского. Морфологию и синтаксис, да, интересно посмотреть.

**Comment by kuk** [comment]
Добавил https://github.com/natasha/naeval/commit/2e87e68b340954de04b98cfde096700cfea311f6

Общие впечатления: академическая разработка, хорошее качество, низкая скорость, не очень удобный интерфейс. Статья https://arxiv.org/pdf/2003.07082.pdf

Морфология
![image](https://user-images.githubusercontent.com/153776/85365449-0b3ea780-b52e-11ea-9924-91d15c1ef6ca.png)

Синтаксис
Отличное качество, очень низкая скорость и на GPU и на CPU. Алгоритм тот же что в Slovnet на качество значительно лучше. Может быть дело в

> We
> further augment this model with two linguistically
> motivated features: one that predicts the linearization order of two words in a given language, and
> the other that predicts the typical distance in linear
> order between them. We have previously shown
> that these features significantly improve parsing
> accuracy (Qi et al., 2018)
> 

![image](https://user-images.githubusercontent.com/153776/85365522-3628fb80-b52e-11ea-8889-96385d45c786.png)

NER
Среднее качество, удивительно что так хорошо на WikiNER. Оооочень медленно даже на GPU. Возможно из-за CharLSTM

> For NER
> we adopt the contextualized string representationbased sequence tagger from Akbik et al. (2018).
> We first train a forward and a backward characterlevel LSTM language model, and at tagging time
> we concatenate the representations at the end of
> each word position from both language models
> with word embeddings, and feed the result into a
> standard one-layer Bi-LSTM sequence tagger with
> a conditional random field (CRF)-based decoder.

![image](https://user-images.githubusercontent.com/153776/85365834-ca935e00-b52e-11ea-9fd0-48f0008d3c04.png)

**Comment by lexmosolov** [comment]
Интересно сравнение качества по NER модели Google Cloud Natural Language

**Comment by kuk** [comment]
@lexmosolov Naeval сравнивает открытые решения. Грубо говоря инструменты, которые можно скачать и запустить у себя на компьютере. 

Может быть отдельно нужно будет сравнить коробочные продукты и сервисы типа Google Cloud Natural Language
