### ISSUE TITLE
Добавьте пожалуйста привычный всем syntagrus в тесты для POS и DEP.

### ISSUE THREAD

**Issue by buriy** [natasha/naeval#2]

**Comment by kuk** [comment]
Колонка fiction в https://github.com/natasha/naeval#morphology-taggers https://github.com/natasha/naeval#syntax-parser это это и есть Syntagrus из https://github.com/dialogue-evaluation/GramEval2020/tree/master/dataTrain

Почему используется версия Syntagrus от GramEval2020 а не стандартная из UD. 1. Slovnet BERT учился на данные GramEval2020. Да, я понимаю это не совсем честно, другие системы учились на версии UD. 2. Важно проверить качество на новостях, в UD нет текстов этой тематики

**Comment by buriy** [comment]
Спасибо! Надо это где-то пометить в FAQ по этим колонкам, что ли. А то если я был не в курсе... (я лишь немного не успел поучаствовать в этой дорожке).
А то, что тестируется версия на UD 2.5 -- это норм, за исключением морф тегов, т.е. пока ты измеряешь только POS-tagging, результаты не должны сильно поменяться.

**Comment by kuk** [comment]
Добавил https://github.com/natasha/slovnet#morphology-1
