### ISSUE TITLE
Добавить скорость BERT и Slovnet-BERT на CPU, а для GPU сделать отдельную колонку

### ISSUE THREAD

**Issue by buriy** [natasha/naeval#4]
(У spacy тоже есть два режима -- CPU и GPU, которые в несколько раз по скорости отличаются...)

**Comment by kuk** [comment]
Посчитал разово. Spacy на GPU не мерил.

DeepPavlov BERT NER ~1 статья/сек на CPU, Slovnet BERT NER — ~2. Разница с GPU в ~15 раз.
![image](https://user-images.githubusercontent.com/153776/85288619-b273fe00-b49e-11ea-9310-bc6b31ecbd68.png)

**Comment by buriy** [comment]
Классно, достаточно и один раз посчитать. Будут теперь более точные оценочные цифры для ресёрча и для презентаций.
